ERROR -1 2104 Market data farm connection is OK:cashfarm
ERROR -1 2104 Market data farm connection is OK:usfarm
ERROR -1 2106 HMDS data farm connection is OK:ushmds
ERROR -1 2158 Sec-def data farm connection is OK:secdefil
ERROR -1 2108 Market data farm connection is inactive but should be available upon demand.cashfarm
ERROR -1 2108 Market data farm connection is inactive but should be available upon demand.cashfarm
ERROR -1 1100 Connectivity between IB and Trader Workstation has been lost.
ERROR -1 2157 Sec-def data farm connection is broken:secdefil
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
ERROR -1 2103 Market data farm connection is broken:usfarm
ERROR -1 2158 Sec-def data farm connection is OK:secdefil
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
ERROR -1 2104 Market data farm connection is OK:usfarm
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
ERROR -1 2105 HMDS data farm connection is broken:ushmds
ERROR -1 2106 HMDS data farm connection is OK:ushmds
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
Traceback (most recent call last):
  File "/Users/colakamornik/PycharmProjects/algotrader/Main.py", line 332, in update_ui
    total_positions_value += p["Value"]
KeyError: 'Value'
ERROR -1 2104 Market data farm connection is OK:usfarm
ERROR -1 2106 HMDS data farm connection is OK:ushmds
ERROR -1 2158 Sec-def data farm connection is OK:secdefil
ERROR -1 1100 Connectivity between IB and Trader Workstation has been lost.
ERROR -1 2157 Sec-def data farm connection is broken:secdefil
ERROR -1 2158 Sec-def data farm connection is OK:secdefil
ERROR -1 2103 Market data farm connection is broken:usfarm
ERROR -1 2104 Market data farm connection is OK:usfarm
ERROR -1 2105 HMDS data farm connection is broken:ushmds
ERROR -1 2106 HMDS data farm connection is OK:ushmds
ERROR -1 1102 Connectivity between IB and Trader Workstation has been restored - data maintained. All data farms are connected: usfarm; ushmds; secdefil.
